import type { Achievement } from "../types";

export const achievements: Achievement[] = [
  {
    id: "first-recovered-signal",
    name: "First Recovered Signal",
    description: "Stabilize your first practice transmission.",
    rarity: "common",
    icon: "signal",
    condition: { type: "task-count", count: 1 },
    discoveryText: "A faint pulse answers from the archive.",
  },
  {
    id: "fragment-reader",
    name: "Fragment Reader",
    description: "Restore your first complete lesson fragment.",
    rarity: "common",
    icon: "fragment",
    condition: { type: "lesson-count", count: 1 },
  },
  {
    id: "logic-excavator",
    name: "Logic Excavator",
    description: "Recover the entire Logic Chambers sector.",
    rarity: "rare",
    icon: "compass",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "logic-chambers",
    },
    discoveryText: "Conditional pathways converge into a stable reasoning lattice.",
  },
  {
    id: "loop-resonator",
    name: "Loop Resonator",
    description: "Complete the loop reconstruction fragment.",
    rarity: "uncommon",
    icon: "orbit",
    condition: { type: "lesson-completed", lessonId: "python-loops" },
  },
  {
    id: "memory-cartographer",
    name: "Memory Cartographer",
    description: "Map every fragment inside Memory Structures.",
    rarity: "rare",
    icon: "map",
    condition: {
      type: "world-completed",
      trackId: "python",
      worldId: "memory-structures",
    },
  },
  {
    id: "hidden-channel",
    name: "Hidden Channel",
    description: "Recover three optional bonus transmissions.",
    rarity: "uncommon",
    icon: "key",
    condition: { type: "bonus-count", count: 3 },
  },
  {
    id: "pulse-keeper",
    name: "Pulse Keeper",
    description: "Maintain a three-day Pulse Chain.",
    rarity: "rare",
    icon: "pulse",
    condition: { type: "streak", days: 3 },
  },
  {
    id: "archive-restorer",
    name: "Archive Restorer",
    description: "Restore the complete Python Core expedition.",
    rarity: "mythic",
    icon: "core",
    condition: { type: "track-completed", trackId: "python" },
    discoveryText: "The dormant organism recognizes you as a core restorer.",
  },
  {
    id: "signal-conductor",
    name: "Signal Conductor",
    description: "Accumulate 1,000 units of recovered Signal Energy.",
    rarity: "mythic",
    icon: "conductor",
    condition: { type: "total-xp", amount: 1000 },
  },
];
